sudo: required

services:
    - docker

before_install:
    - docker build -t mozilla/onyx .
    
script:
    - docker run mozilla/onyx /bin/sh -c "pip install -r requirements-dev.txt; fab build"

after_success:
  - coveralls
